/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  applecalendar: import("./applecalendar/api"),
  caldavcalendar: import("./caldavcalendar/api"),
  exchange2013calendar: import("./exchange2013calendar/api"),
  exchange2016calendar: import("./exchange2016calendar/api"),
  exchangecalendar: import("./exchangecalendar/api"),
  feishucalendar: import("./feishucalendar/api"),
  googlecalendar: import("./googlecalendar/api"),
  googlevideo: import("./googlevideo/api"),
  "ics-feedcalendar": import("./ics-feedcalendar/api"),
  larkcalendar: import("./larkcalendar/api"),
  office365calendar: import("./office365calendar/api"),
  "routing-forms": import("./routing-forms/api"),
  sendgrid: import("./sendgrid/api"),
  stripepayment: import("./stripepayment/api"),
  basic: import("./templates/basic/api"),
  "booking-pages-tag": import("./templates/booking-pages-tag/api"),
  "event-type-app-card": import("./templates/event-type-app-card/api"),
  "event-type-location-video-static": import("./templates/event-type-location-video-static/api"),
  "general-app-settings": import("./templates/general-app-settings/api"),
  zohocalendar: import("./zohocalendar/api"),
  zoomvideo: import("./zoomvideo/api"),
};
